//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kis.Noris.Api.Service_References.Rosminzdrav.Nsi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:service", ConfigurationName="Rosminzdrav.Nsi.service")]
    public interface service {
        
        // CODEGEN: Parameter 'getServerTimeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getServerTime", ReplyAction="urn:service:service:getServerTimeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getServerTimeReturn")]
        getServerTimeResponse getServerTime(getServerTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getServerTime", ReplyAction="urn:service:service:getServerTimeResponse")]
        System.Threading.Tasks.Task<getServerTimeResponse> getServerTimeAsync(getServerTimeRequest request);
        
        // CODEGEN: Parameter 'getRefbookListReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookList", ReplyAction="urn:service:service:getRefbookListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookListReturn")]
        getRefbookListResponse getRefbookList(getRefbookListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookList", ReplyAction="urn:service:service:getRefbookListResponse")]
        System.Threading.Tasks.Task<getRefbookListResponse> getRefbookListAsync(getRefbookListRequest request);
        
        // CODEGEN: Parameter 'getVersionListReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getVersionList", ReplyAction="urn:service:service:getVersionListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionListReturn")]
        getVersionListResponse getVersionList(getVersionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getVersionList", ReplyAction="urn:service:service:getVersionListResponse")]
        System.Threading.Tasks.Task<getVersionListResponse> getVersionListAsync(getVersionListRequest request);
        
        // CODEGEN: Parameter 'getRefbookReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbook", ReplyAction="urn:service:service:getRefbookResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookReturn")]
        getRefbookResponse getRefbook(getRefbookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbook", ReplyAction="urn:service:service:getRefbookResponse")]
        System.Threading.Tasks.Task<getRefbookResponse> getRefbookAsync(getRefbookRequest request);
        
        // CODEGEN: Parameter 'getRefbookPartsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookParts", ReplyAction="urn:service:service:getRefbookPartsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookPartsReturn")]
        getRefbookPartsResponse getRefbookParts(getRefbookPartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookParts", ReplyAction="urn:service:service:getRefbookPartsResponse")]
        System.Threading.Tasks.Task<getRefbookPartsResponse> getRefbookPartsAsync(getRefbookPartsRequest request);
        
        // CODEGEN: Parameter 'getRefbookPartialReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookPartial", ReplyAction="urn:service:service:getRefbookPartialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookPartialReturn")]
        getRefbookPartialResponse getRefbookPartial(getRefbookPartialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookPartial", ReplyAction="urn:service:service:getRefbookPartialResponse")]
        System.Threading.Tasks.Task<getRefbookPartialResponse> getRefbookPartialAsync(getRefbookPartialRequest request);
        
        // CODEGEN: Parameter 'getRefbookUpdateReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookUpdate", ReplyAction="urn:service:service:getRefbookUpdateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookUpdateReturn")]
        getRefbookUpdateResponse getRefbookUpdate(getRefbookUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookUpdate", ReplyAction="urn:service:service:getRefbookUpdateResponse")]
        System.Threading.Tasks.Task<getRefbookUpdateResponse> getRefbookUpdateAsync(getRefbookUpdateRequest request);
        
        // CODEGEN: Parameter 'getRefbookStructureReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookStructure", ReplyAction="urn:service:service:getRefbookStructureResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefbookStructureReturn")]
        getRefbookStructureResponse getRefbookStructure(getRefbookStructureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRefbookStructure", ReplyAction="urn:service:service:getRefbookStructureResponse")]
        System.Threading.Tasks.Task<getRefbookStructureResponse> getRefbookStructureAsync(getRefbookStructureRequest request);
        
        // CODEGEN: Parameter 'getRecordHistoryReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRecordHistory", ReplyAction="urn:service:service:getRecordHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRecordHistoryReturn")]
        getRecordHistoryResponse getRecordHistory(getRecordHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getRecordHistory", ReplyAction="urn:service:service:getRecordHistoryResponse")]
        System.Threading.Tasks.Task<getRecordHistoryResponse> getRecordHistoryAsync(getRecordHistoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerTime", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getServerTimeRequest {
        
        public getServerTimeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerTimeResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getServerTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string getServerTimeReturn;
        
        public getServerTimeResponse() {
        }
        
        public getServerTimeResponse(string getServerTimeReturn) {
            this.getServerTimeReturn = getServerTimeReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:service")]
    public partial class ArrayOfMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Map[] itemField;
        
        private string hrefField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Map[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:service")]
    public partial class Map : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArrayOfMap childrenField;
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
                this.RaisePropertyChanged("children");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookList", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey1;
        
        public getRefbookListRequest() {
        }
        
        public getRefbookListRequest(string userKey1) {
            this.userKey1 = userKey1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookListResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookListReturn;
        
        public getRefbookListResponse() {
        }
        
        public getRefbookListResponse(ArrayOfMap getRefbookListReturn) {
            this.getRefbookListReturn = getRefbookListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionList", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getVersionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode4;
        
        public getVersionListRequest() {
        }
        
        public getVersionListRequest(string userKey5, string refbookCode4) {
            this.userKey5 = userKey5;
            this.refbookCode4 = refbookCode4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionListResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getVersionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getVersionListReturn;
        
        public getVersionListResponse() {
        }
        
        public getVersionListResponse(ArrayOfMap getVersionListReturn) {
            this.getVersionListReturn = getVersionListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbook", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version;
        
        public getRefbookRequest() {
        }
        
        public getRefbookRequest(string userKey, string refbookCode, string version) {
            this.userKey = userKey;
            this.refbookCode = refbookCode;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookReturn;
        
        public getRefbookResponse() {
        }
        
        public getRefbookResponse(ArrayOfMap getRefbookReturn) {
            this.getRefbookReturn = getRefbookReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookParts", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookPartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version2;
        
        public getRefbookPartsRequest() {
        }
        
        public getRefbookPartsRequest(string userKey3, string refbookCode2, string version2) {
            this.userKey3 = userKey3;
            this.refbookCode2 = refbookCode2;
            this.version2 = version2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookPartsResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookPartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookPartsReturn;
        
        public getRefbookPartsResponse() {
        }
        
        public getRefbookPartsResponse(ArrayOfMap getRefbookPartsReturn) {
            this.getRefbookPartsReturn = getRefbookPartsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookPartial", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookPartialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string partNumber;
        
        public getRefbookPartialRequest() {
        }
        
        public getRefbookPartialRequest(string userKey2, string refbookCode1, string version1, string partNumber) {
            this.userKey2 = userKey2;
            this.refbookCode1 = refbookCode1;
            this.version1 = version1;
            this.partNumber = partNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookPartialResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookPartialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookPartialReturn;
        
        public getRefbookPartialResponse() {
        }
        
        public getRefbookPartialResponse(ArrayOfMap getRefbookPartialReturn) {
            this.getRefbookPartialReturn = getRefbookPartialReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookUpdate", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newVersion;
        
        public getRefbookUpdateRequest() {
        }
        
        public getRefbookUpdateRequest(string userKey4, string refbookCode3, string userVersion, string newVersion) {
            this.userKey4 = userKey4;
            this.refbookCode3 = refbookCode3;
            this.userVersion = userVersion;
            this.newVersion = newVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookUpdateResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookUpdateReturn;
        
        public getRefbookUpdateResponse() {
        }
        
        public getRefbookUpdateResponse(ArrayOfMap getRefbookUpdateReturn) {
            this.getRefbookUpdateReturn = getRefbookUpdateReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookStructure", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookStructureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode6;
        
        public getRefbookStructureRequest() {
        }
        
        public getRefbookStructureRequest(string userKey7, string refbookCode6) {
            this.userKey7 = userKey7;
            this.refbookCode6 = refbookCode6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRefbookStructureResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRefbookStructureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRefbookStructureReturn;
        
        public getRefbookStructureResponse() {
        }
        
        public getRefbookStructureResponse(ArrayOfMap getRefbookStructureReturn) {
            this.getRefbookStructureReturn = getRefbookStructureReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecordHistory", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRecordHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userKey6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refbookCode5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string rowIdent;
        
        public getRecordHistoryRequest() {
        }
        
        public getRecordHistoryRequest(string userKey6, string refbookCode5, string rowIdent) {
            this.userKey6 = userKey6;
            this.refbookCode5 = refbookCode5;
            this.rowIdent = rowIdent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecordHistoryResponse", WrapperNamespace="urn:service", IsWrapped=true)]
    public partial class getRecordHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfMap getRecordHistoryReturn;
        
        public getRecordHistoryResponse() {
        }
        
        public getRecordHistoryResponse(ArrayOfMap getRecordHistoryReturn) {
            this.getRecordHistoryReturn = getRecordHistoryReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceChannel : service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceClient : System.ServiceModel.ClientBase<service>, service {
        
        public serviceClient() {
        }
        
        public serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getServerTimeResponse service.getServerTime(getServerTimeRequest request) {
            return base.Channel.getServerTime(request);
        }
        
        public string getServerTime() {
            getServerTimeRequest inValue = new getServerTimeRequest();
            getServerTimeResponse retVal = ((service)(this)).getServerTime(inValue);
            return retVal.getServerTimeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getServerTimeResponse> service.getServerTimeAsync(getServerTimeRequest request) {
            return base.Channel.getServerTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<getServerTimeResponse> getServerTimeAsync() {
            getServerTimeRequest inValue = new getServerTimeRequest();
            return ((service)(this)).getServerTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookListResponse service.getRefbookList(getRefbookListRequest request) {
            return base.Channel.getRefbookList(request);
        }
        
        public ArrayOfMap getRefbookList(string userKey1) {
            getRefbookListRequest inValue = new getRefbookListRequest();
            inValue.userKey1 = userKey1;
            getRefbookListResponse retVal = ((service)(this)).getRefbookList(inValue);
            return retVal.getRefbookListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookListResponse> service.getRefbookListAsync(getRefbookListRequest request) {
            return base.Channel.getRefbookListAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookListResponse> getRefbookListAsync(string userKey1) {
            getRefbookListRequest inValue = new getRefbookListRequest();
            inValue.userKey1 = userKey1;
            return ((service)(this)).getRefbookListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getVersionListResponse service.getVersionList(getVersionListRequest request) {
            return base.Channel.getVersionList(request);
        }
        
        public ArrayOfMap getVersionList(string userKey5, string refbookCode4) {
            getVersionListRequest inValue = new getVersionListRequest();
            inValue.userKey5 = userKey5;
            inValue.refbookCode4 = refbookCode4;
            getVersionListResponse retVal = ((service)(this)).getVersionList(inValue);
            return retVal.getVersionListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getVersionListResponse> service.getVersionListAsync(getVersionListRequest request) {
            return base.Channel.getVersionListAsync(request);
        }
        
        public System.Threading.Tasks.Task<getVersionListResponse> getVersionListAsync(string userKey5, string refbookCode4) {
            getVersionListRequest inValue = new getVersionListRequest();
            inValue.userKey5 = userKey5;
            inValue.refbookCode4 = refbookCode4;
            return ((service)(this)).getVersionListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookResponse service.getRefbook(getRefbookRequest request) {
            return base.Channel.getRefbook(request);
        }
        
        public ArrayOfMap getRefbook(string userKey, string refbookCode, string version) {
            getRefbookRequest inValue = new getRefbookRequest();
            inValue.userKey = userKey;
            inValue.refbookCode = refbookCode;
            inValue.version = version;
            getRefbookResponse retVal = ((service)(this)).getRefbook(inValue);
            return retVal.getRefbookReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookResponse> service.getRefbookAsync(getRefbookRequest request) {
            return base.Channel.getRefbookAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookResponse> getRefbookAsync(string userKey, string refbookCode, string version) {
            getRefbookRequest inValue = new getRefbookRequest();
            inValue.userKey = userKey;
            inValue.refbookCode = refbookCode;
            inValue.version = version;
            return ((service)(this)).getRefbookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookPartsResponse service.getRefbookParts(getRefbookPartsRequest request) {
            return base.Channel.getRefbookParts(request);
        }
        
        public ArrayOfMap getRefbookParts(string userKey3, string refbookCode2, string version2) {
            getRefbookPartsRequest inValue = new getRefbookPartsRequest();
            inValue.userKey3 = userKey3;
            inValue.refbookCode2 = refbookCode2;
            inValue.version2 = version2;
            getRefbookPartsResponse retVal = ((service)(this)).getRefbookParts(inValue);
            return retVal.getRefbookPartsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookPartsResponse> service.getRefbookPartsAsync(getRefbookPartsRequest request) {
            return base.Channel.getRefbookPartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookPartsResponse> getRefbookPartsAsync(string userKey3, string refbookCode2, string version2) {
            getRefbookPartsRequest inValue = new getRefbookPartsRequest();
            inValue.userKey3 = userKey3;
            inValue.refbookCode2 = refbookCode2;
            inValue.version2 = version2;
            return ((service)(this)).getRefbookPartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookPartialResponse service.getRefbookPartial(getRefbookPartialRequest request) {
            return base.Channel.getRefbookPartial(request);
        }
        
        public ArrayOfMap getRefbookPartial(string userKey2, string refbookCode1, string version1, string partNumber) {
            getRefbookPartialRequest inValue = new getRefbookPartialRequest();
            inValue.userKey2 = userKey2;
            inValue.refbookCode1 = refbookCode1;
            inValue.version1 = version1;
            inValue.partNumber = partNumber;
            getRefbookPartialResponse retVal = ((service)(this)).getRefbookPartial(inValue);
            return retVal.getRefbookPartialReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookPartialResponse> service.getRefbookPartialAsync(getRefbookPartialRequest request) {
            return base.Channel.getRefbookPartialAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookPartialResponse> getRefbookPartialAsync(string userKey2, string refbookCode1, string version1, string partNumber) {
            getRefbookPartialRequest inValue = new getRefbookPartialRequest();
            inValue.userKey2 = userKey2;
            inValue.refbookCode1 = refbookCode1;
            inValue.version1 = version1;
            inValue.partNumber = partNumber;
            return ((service)(this)).getRefbookPartialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookUpdateResponse service.getRefbookUpdate(getRefbookUpdateRequest request) {
            return base.Channel.getRefbookUpdate(request);
        }
        
        public ArrayOfMap getRefbookUpdate(string userKey4, string refbookCode3, string userVersion, string newVersion) {
            getRefbookUpdateRequest inValue = new getRefbookUpdateRequest();
            inValue.userKey4 = userKey4;
            inValue.refbookCode3 = refbookCode3;
            inValue.userVersion = userVersion;
            inValue.newVersion = newVersion;
            getRefbookUpdateResponse retVal = ((service)(this)).getRefbookUpdate(inValue);
            return retVal.getRefbookUpdateReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookUpdateResponse> service.getRefbookUpdateAsync(getRefbookUpdateRequest request) {
            return base.Channel.getRefbookUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookUpdateResponse> getRefbookUpdateAsync(string userKey4, string refbookCode3, string userVersion, string newVersion) {
            getRefbookUpdateRequest inValue = new getRefbookUpdateRequest();
            inValue.userKey4 = userKey4;
            inValue.refbookCode3 = refbookCode3;
            inValue.userVersion = userVersion;
            inValue.newVersion = newVersion;
            return ((service)(this)).getRefbookUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRefbookStructureResponse service.getRefbookStructure(getRefbookStructureRequest request) {
            return base.Channel.getRefbookStructure(request);
        }
        
        public ArrayOfMap getRefbookStructure(string userKey7, string refbookCode6) {
            getRefbookStructureRequest inValue = new getRefbookStructureRequest();
            inValue.userKey7 = userKey7;
            inValue.refbookCode6 = refbookCode6;
            getRefbookStructureResponse retVal = ((service)(this)).getRefbookStructure(inValue);
            return retVal.getRefbookStructureReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRefbookStructureResponse> service.getRefbookStructureAsync(getRefbookStructureRequest request) {
            return base.Channel.getRefbookStructureAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRefbookStructureResponse> getRefbookStructureAsync(string userKey7, string refbookCode6) {
            getRefbookStructureRequest inValue = new getRefbookStructureRequest();
            inValue.userKey7 = userKey7;
            inValue.refbookCode6 = refbookCode6;
            return ((service)(this)).getRefbookStructureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getRecordHistoryResponse service.getRecordHistory(getRecordHistoryRequest request) {
            return base.Channel.getRecordHistory(request);
        }
        
        public ArrayOfMap getRecordHistory(string userKey6, string refbookCode5, string rowIdent) {
            getRecordHistoryRequest inValue = new getRecordHistoryRequest();
            inValue.userKey6 = userKey6;
            inValue.refbookCode5 = refbookCode5;
            inValue.rowIdent = rowIdent;
            getRecordHistoryResponse retVal = ((service)(this)).getRecordHistory(inValue);
            return retVal.getRecordHistoryReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getRecordHistoryResponse> service.getRecordHistoryAsync(getRecordHistoryRequest request) {
            return base.Channel.getRecordHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<getRecordHistoryResponse> getRecordHistoryAsync(string userKey6, string refbookCode5, string rowIdent) {
            getRecordHistoryRequest inValue = new getRecordHistoryRequest();
            inValue.userKey6 = userKey6;
            inValue.refbookCode5 = refbookCode5;
            inValue.rowIdent = rowIdent;
            return ((service)(this)).getRecordHistoryAsync(inValue);
        }
    }
}
